spring.application.name=SpringEcom

spring.datasource.url=jdbc:postgresql://localhost:5432/ljava
spring.datasource.username=postgres
spring.datasource.password=Balasiva@2025
spring.jpa.hibernate.ddl-auto=update
